yatube/about/urls.py
from django.urls import path

from about import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path, reverse_lazy

from users import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html',
            success_url=reverse_lazy('users:password_change_done')
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
            success_url=reverse_lazy('users:password_reset_done')
        ),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy('users:password_reset_complete')
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler400 = 'core.views.bad_request'
handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from users.forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/users/auth_base.html
{% extends "base.html" %}
{% block title %}{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% block card_header %}{% endblock card_header %}
        </div>
        <div class="card-body">
          {% block card_body %}{% endblock card_body %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/logged_out.html
{% extends "users/auth_base.html" %}
{% block title %}Вы вышли из системы{% endblock %}
{% block card_header %}
  Выход
{% endblock %}
{% block card_body %}
  <p>
    Вы вышли из своей учётной записи. Ждём вас снова!
  </p>
{% endblock %}

yatube/templates/users/login.html
{% extends "users/auth_base.html" %}
{% block title %}Войти{% endblock %}
{% block card_header %}
  Войти на сайт
{% endblock %}
{% block card_body %}
  {% include 'includes/form_error.html' %}
  {% include 'users/includes/auth_form.html' with forgot_password=True %}
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends "users/auth_base.html" %}
{% block title %}Пароль изменён{% endblock %}
{% block card_header %}
  Пароль изменён
{% endblock %}
{% block card_body %}
  <p>Пароль изменён успешно</p>
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends "users/auth_base.html" %}
{% block title %}Изменение пароля{% endblock %}
{% block card_header %}
  Изменить пароль
{% endblock %}
{% block card_body %}
  {% include 'includes/form_error.html' %}
  {% include 'users/includes/auth_form.html' with button_name='Изменить пароль' %}
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends "users/auth_base.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block card_header %}
  Восстановление пароля завершено
{% endblock %}
{% block card_body %}
  <p>Ваш пароль был сохранен. Используйте его для входа</p>
  <a href="{% url 'users:login' %}">войти</a>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends "users/auth_base.html" %}
{% block title %}Новый пароль{% endblock %}
{% block card_header %}
  {% if validlink %}
    Введите новый пароль
  {% else %}
    Ошибка
  {% endif %}
{% endblock %}
{% block card_body %}
  {% if validlink %}
    {% include 'includes/form_error.html' %}
    {% include 'users/includes/auth_form.html' with button_name='Назначить новый пароль' %}
  {% else %}
    <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
  {% endif %}
{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends "users/auth_base.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block card_header %}
  Отправлено письмо
{% endblock %}
{% block card_body %}
  <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends "users/auth_base.html" %}
{% block title %}Сброс пароля{% endblock %}
{% block card_header %}
  Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
{% endblock %}
{% block card_body %}
  {% include 'includes/form_error.html' %}
  {% include 'users/includes/auth_form.html' with button_name='Сбросить пароль' %}
{% endblock %}

yatube/templates/users/signup.html
{% extends "users/auth_base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block card_header %}
  Зарегистрироваться
{% endblock %}
{% block card_body %}
  {% include 'includes/form_error.html' %}
  {% include 'users/includes/auth_form.html' with button_name='Зарегистрироваться' %}
{% endblock %}